// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselineEntry } from "./BaselineEntry";

export type Baseline = { version: number, created: string, entries: Array<BaselineEntry>, };
