// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingKind } from "./FindingKind";
import type { Severity } from "./Severity";

export type BaselineEntry = { id: string, kind: FindingKind, severity: Severity, headline: string, files: Array<string>, note?: string | null, };
