// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";

export type CaseMismatch = { from: FileId, specifier: string, line: number, actual: string, };
