// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefKind = "function" | "class" | "struct" | "enum" | "trait" | "interface" | "typeAlias" | "const" | "impl" | "module";
