// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";
import type { ImportSite } from "./ImportSite";

export type EdgeDetail = { from: number, to: number, fromPath: string, toPath: string, kind: EdgeKind, sites: Array<ImportSite>, };
