// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";

export type EdgeSite = { from: FileId, to: FileId, import: number, };
