// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";
import type { FileId } from "./FileId";

export type Edge = { from: FileId, to: FileId, kind: EdgeKind, weight: number, };
