// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileHistory = { commits: number, lastTouched: bigint, firstTouched: bigint, authors: number, topAuthorShare: number, topAuthor: string, };
