// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { Language } from "./Language";
import type { ModuleId } from "./ModuleId";

export type FileNode = { id: FileId, path: string, module: ModuleId, language: Language, loc: number, bytes: bigint, contentHash: string, };
