// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";

export type FindingPage = { total: number, rows: Array<Finding>, indices: Array<number>, isAccepted: Array<boolean>, accepted: number, };
