// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";
import type { FileId } from "./FileId";
import type { FindingKind } from "./FindingKind";
import type { Severity } from "./Severity";

export type Finding = { kind: FindingKind, severity: Severity, score: number, headline: string, files: Array<FileId>, evidence: Array<Evidence>, why: string, howToFix: string, };
