// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindingKind = "cycle" | "godFile" | "orphan" | "unstableInterface" | "layeringViolation" | "busFactor" | "distantCoupling" | "barrelHub" | "caseMismatch" | "lspDisagreement" | "pathAlias";
