// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeDto } from "./EdgeDto";
import type { ModuleDto } from "./ModuleDto";
import type { NodeDto } from "./NodeDto";

export type GraphPayload = { nodes: Array<NodeDto>, edges: Array<EdgeDto>, modules: Array<ModuleDto>, };
