// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportSite = { line: number, specifier: string, kind: string, typeOnly: boolean, };
