// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";

export type LspRepair = { from: FileId, specifier: string, line: number, to: FileId, server: string, };
