// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspReport = { servers: Array<string>, failed: Array<string>, queries: number, repaired: number, disagreements: number, unlocatable: number, truncated: boolean, };
