// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspServerDto = { id: string, label: string, command: string, installed: boolean, applicable: boolean, };
