// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspMode } from "./LspMode";

export type LspSettings = { mode: LspMode, timeoutMs: bigint, startupMs: bigint, budgetMs: bigint, servers: Array<string>, };
