// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { ModuleId } from "./ModuleId";

export type ModuleNode = { id: ModuleId, path: string, files: Array<FileId>, };
