// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModuleDto = { id: number, path: string, name: string, fileCount: number, loc: number, };
