// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

export type NodeDto = { id: number, path: string, name: string, module: number, language: Language, loc: number, fanIn: number, fanOut: number, churn: number, authors: number, heat: number, };
