// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { Language } from "./Language";
import type { NodeRef } from "./NodeRef";
import type { UnresolvedDto } from "./UnresolvedDto";

export type NodeDetail = { id: number, path: string, language: Language, loc: number, bytes: bigint, module: string, fanIn: number, fanOut: number, churn: number, authors: number, topAuthor: string, topAuthorShare: number, lastTouched: bigint, exports: Array<string>, definitions: number, dependencies: Array<NodeRef>, dependents: Array<NodeRef>, unresolved: Array<UnresolvedDto>, findings: Array<Finding>, };
