// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefSide } from "./RefSide";

export type RefComparison = { base: RefSide, head: RefSide, added: Array<string>, removed: Array<string>, grown: Array<[string, bigint]>, shrunk: Array<[string, bigint]>, cyclesIntroduced: Array<Array<string>>, cyclesResolved: Array<Array<string>>, findingsNew: Array<string>, findingsFixed: Array<string>, skipped: Array<string>, };
