// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefSide = { reference: string, commit: string, files: number, loc: bigint, edges: number, cycles: number, unresolved: number, findings: number, };
