// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspReport } from "./LspReport";

export type ScanSummary = { root: string, name: string, branch: string | null, head: string | null, isGit: boolean, fileCount: number, moduleCount: number, edgeCount: number, totalLoc: bigint, unresolvedCount: number, externalCount: number, findingCount: number, cycleCount: number, commitCount: number, scannedAt: bigint, invalidRules: Array<string>, lsp: LspReport, };
