// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Snapshot = { commit: string, time: bigint, label: string, fileCount: number, totalLoc: number, edgeCount: number, };
