// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolEdge } from "./SymbolEdge";
import type { SymbolNode } from "./SymbolNode";

export type SymbolGraph = { nodes: Array<SymbolNode>, edges: Array<SymbolEdge>, externalRefs: Array<string>, };
