// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefKind } from "./DefKind";
import type { FileId } from "./FileId";

export type SymbolNode = { id: number, name: string, kind: DefKind, file: FileId, path: string, line: number, exported: boolean, };
