// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";

export type UnresolvedReason = { "kind": "external", "detail": string } | { "kind": "noSuchFile", "detail": string } | { "kind": "unmatchedAlias", "detail": string } | { "kind": "dynamicSpecifier" } | { "kind": "reExportChainTooDeep", "detail": string } | { "kind": "noResolverForLanguage", "detail": Language } | { "kind": "excludedFromScan", "detail": string } | { "kind": "fileNotInModuleTree" } | { "kind": "asset", "detail": string };
