// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layer } from "./Layer";
import type { LspSettings } from "./LspSettings";

export type ZatlasConfig = { include: Array<string>, exclude: Array<string>, entrypoints: Array<string>, layers: Array<Layer>, rules: Array<string>, lsp: LspSettings, };
