use std::collections::HashMap;

use crate::findings::{Finding, Severity};
use crate::git::history::FileHistory;
use crate::graph::Adjacency;
use crate::model::{Graph, UnresolvedReason};

pub fn to_markdown(
    graph: &Graph,
    adj: &Adjacency,
    findings: &[Finding],
    history: &HashMap<String, FileHistory>,
    repo_name: &str,
) -> String {
    let mut out = String::new();
    let total_loc: u64 = graph.files.iter().map(|f| f.loc as u64).sum();

    out.push_str(&format!("# {repo_name}\n\n"));
    out.push_str("_Generated by [ZAtlas](https://zsync.eu/zatlas/)._\n\n");

    out.push_str("## At a glance\n\n");
    out.push_str("| | |\n|---|---|\n");
    out.push_str(&format!("| Files | {} |\n", graph.files.len()));
    out.push_str(&format!("| Modules | {} |\n", graph.modules.len()));
    out.push_str(&format!("| Dependencies | {} |\n", graph.edges.len()));
    out.push_str(&format!("| Lines of code | {total_loc} |\n"));
    out.push_str(&format!("| Findings | {} |\n", findings.len()));

    let failures = graph.unresolved_failure_count();
    out.push_str(&format!("| Unresolved imports | {failures} |\n\n"));

    if failures > 0 {
        out.push_str(&format!(
            "> {failures} import{} could not be resolved, so the graph below is \
             incomplete by that much. They are listed at the end.\n\n",
            if failures == 1 { "" } else { "s" }
        ));
    }

    if findings.is_empty() {
        out.push_str(
            "## Findings\n\nNothing to report — no cycles, god files, \
                      orphans or layering violations were found.\n\n",
        );
    } else {
        out.push_str("## Findings\n\n");
        for f in findings {
            out.push_str(&format!(
                "### {} — {}\n\n",
                severity_label(f.severity),
                f.headline
            ));
            if !f.evidence.is_empty() {
                for e in &f.evidence {
                    out.push_str(&format!("- **{}:** {}\n", e.label, e.value));
                }
                out.push('\n');
            }
            out.push_str(&format!("{}\n\n", f.why));
            out.push_str(&format!("**How to fix:** {}\n\n", f.how_to_fix));
        }
    }

    out.push_str("## Most depended upon\n\n");
    out.push_str("| File | Dependents | Lines | Commits |\n|---|---:|---:|---:|\n");
    let mut by_fan_in: Vec<_> = graph.files.iter().map(|f| (adj.fan_in(f.id), f)).collect();
    by_fan_in.sort_by(|a, b| b.0.cmp(&a.0).then_with(|| a.1.path.cmp(&b.1.path)));
    for (n, f) in by_fan_in.iter().take(15) {
        let churn = history.get(&f.path).map(|h| h.commits).unwrap_or(0);
        out.push_str(&format!("| `{}` | {n} | {} | {churn} |\n", f.path, f.loc));
    }
    out.push('\n');

    if !history.is_empty() {
        out.push_str("## Churn hotspots\n\n");
        out.push_str("| File | Commits | Authors | Owner |\n|---|---:|---:|---|\n");
        let mut by_churn: Vec<_> = history.iter().collect();
        by_churn.sort_by(|a, b| b.1.commits.cmp(&a.1.commits).then_with(|| a.0.cmp(b.0)));
        for (path, h) in by_churn.iter().take(15) {
            out.push_str(&format!(
                "| `{path}` | {} | {} | {} ({:.0}%) |\n",
                h.commits,
                h.authors,
                h.top_author,
                h.top_author_share * 100.0
            ));
        }
        out.push('\n');
    }

    if failures > 0 {
        out.push_str("## Unresolved imports\n\n");
        out.push_str(
            "These are stated rather than hidden: the graph does not \
                      include them.\n\n",
        );
        out.push_str("| File | Line | Import | Why |\n|---|---:|---|---|\n");
        for u in graph.unresolved.iter().filter(|u| {
            !matches!(
                u.reason,
                UnresolvedReason::External(_)
                    | UnresolvedReason::Asset(_)
                    | UnresolvedReason::ExcludedFromScan(_)
                    | UnresolvedReason::NoResolverForLanguage(_)
            )
        }) {
            let path = graph.file(u.from).map(|f| f.path.as_str()).unwrap_or("?");
            out.push_str(&format!(
                "| `{path}` | {} | `{}` | {} |\n",
                u.line,
                u.specifier,
                reason_label(&u.reason)
            ));
        }
        out.push('\n');
    }

    out
}

fn severity_label(s: Severity) -> &'static str {
    match s {
        Severity::Critical => "Critical",
        Severity::High => "High",
        Severity::Medium => "Medium",
        Severity::Low => "Low",
        Severity::Info => "Info",
    }
}

fn reason_label(r: &UnresolvedReason) -> &'static str {
    match r {
        UnresolvedReason::External(_) => "external package",
        UnresolvedReason::Asset(_) => "asset",
        UnresolvedReason::ExcludedFromScan(_) => "excluded from the scan",
        UnresolvedReason::NoSuchFile(_) => "no such file",
        UnresolvedReason::UnmatchedAlias(_) => "alias points nowhere",
        UnresolvedReason::DynamicSpecifier => "computed at runtime",
        UnresolvedReason::ReExportChainTooDeep(_) => "re-export chain too deep",
        UnresolvedReason::NoResolverForLanguage(_) => "no resolver for this language",
        UnresolvedReason::FileNotInModuleTree => "file is not part of any crate",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::findings::{Evidence, FindingKind};
    use crate::model::{Edge, EdgeKind, FileId, FileNode, Language, ModuleId, UnresolvedImport};

    fn graph() -> Graph {
        Graph {
            files: vec![
                FileNode {
                    id: FileId(0),
                    path: "src/a.ts".into(),
                    module: ModuleId(0),
                    language: Language::TypeScript,
                    loc: 100,
                    bytes: 1,
                    content_hash: String::new(),
                },
                FileNode {
                    id: FileId(1),
                    path: "src/b.ts".into(),
                    module: ModuleId(0),
                    language: Language::TypeScript,
                    loc: 20,
                    bytes: 1,
                    content_hash: String::new(),
                },
            ],
            edges: vec![Edge {
                from: FileId(0),
                to: FileId(1),
                kind: EdgeKind::Import,
                weight: 1.0,
            }],
            ..Default::default()
        }
    }

    fn finding() -> Finding {
        Finding {
            kind: FindingKind::Cycle,
            severity: Severity::High,
            score: 0.9,
            headline: "Cycle across 2 files".into(),
            files: vec![FileId(0), FileId(1)],
            evidence: vec![Evidence::new("Files in cycle", 2)],
            why: "They depend on each other in a loop.".into(),
            how_to_fix: "Invert the accidental edge.".into(),
        }
    }

    fn render(g: &Graph, findings: &[Finding]) -> String {
        let adj = Adjacency::build(g.files.len(), &g.edges);
        to_markdown(g, &adj, findings, &HashMap::new(), "demo")
    }

    #[test]
    fn the_report_leads_with_the_repository_and_its_totals() {
        let r = render(&graph(), &[]);
        assert!(r.starts_with("# demo"));
        assert!(r.contains("| Files | 2 |"), "{r}");
        assert!(r.contains("| Lines of code | 120 |"), "{r}");
    }

    #[test]
    fn every_finding_carries_its_evidence_and_its_fix_into_the_report() {
        let r = render(&graph(), &[finding()]);
        assert!(r.contains("Cycle across 2 files"), "{r}");
        assert!(r.contains("**Files in cycle:** 2"), "{r}");
        assert!(r.contains("They depend on each other in a loop."), "{r}");
        assert!(
            r.contains("**How to fix:** Invert the accidental edge."),
            "{r}"
        );
    }

    #[test]
    fn a_clean_repository_says_so_rather_than_leaving_a_blank_section() {
        let r = render(&graph(), &[]);
        assert!(r.contains("Nothing to report"), "{r}");
    }

    #[test]
    fn unresolved_imports_are_declared_up_front_and_listed() {
        let mut g = graph();
        g.unresolved.push(UnresolvedImport {
            from: FileId(0),
            specifier: "./gone".into(),
            line: 7,
            reason: UnresolvedReason::NoSuchFile("./gone".into()),
        });
        let r = render(&g, &[]);
        assert!(r.contains("the graph below is incomplete"), "{r}");
        assert!(r.contains("## Unresolved imports"), "{r}");
        assert!(r.contains("`./gone`"), "{r}");
        assert!(r.contains("no such file"), "{r}");
    }

    #[test]
    fn external_packages_are_not_listed_as_unresolved() {
        let mut g = graph();
        g.unresolved.push(UnresolvedImport {
            from: FileId(0),
            specifier: "react".into(),
            line: 1,
            reason: UnresolvedReason::External("react".into()),
        });
        let r = render(&g, &[]);
        assert!(r.contains("| Unresolved imports | 0 |"), "{r}");
        assert!(!r.contains("## Unresolved imports"), "{r}");
    }

    #[test]
    fn the_most_depended_upon_table_is_ranked() {
        let r = render(&graph(), &[]);
        let b = r.find("`src/b.ts`").expect("b listed");
        let a = r.find("`src/a.ts`").expect("a listed");
        assert!(b < a, "the file with more dependents comes first");
    }

    #[test]
    fn churn_is_reported_only_when_there_is_history() {
        let g = graph();
        let adj = Adjacency::build(g.files.len(), &g.edges);
        assert!(!to_markdown(&g, &adj, &[], &HashMap::new(), "demo").contains("Churn hotspots"));

        let mut history = HashMap::new();
        history.insert(
            "src/a.ts".to_string(),
            FileHistory {
                commits: 12,
                authors: 2,
                top_author: "Ada".into(),
                top_author_share: 0.75,
                ..Default::default()
            },
        );
        let with = to_markdown(&g, &adj, &[], &history, "demo");
        assert!(with.contains("## Churn hotspots"), "{with}");
        assert!(with.contains("Ada (75%)"), "{with}");
    }

    #[test]
    fn the_report_is_byte_identical_across_runs() {
        let g = graph();
        assert_eq!(render(&g, &[finding()]), render(&g, &[finding()]));
    }
}
